apiVersion: v1
kind: Namespace
metadata:
  name: argocd-extension-installer
  labels:
    app.kubernetes.io/name: argocd-extension-installer
    app.kubernetes.io/component: utility
    framework.version: "4.2.1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-extension-installer
  namespace: argocd-extension-installer
  labels:
    app: argocd-extension-installer
    tier: utility
    component: installer
    framework.version: "4.2.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-extension-installer
  template:
    metadata:
      labels:
        app: argocd-extension-installer
        tier: utility
        component: installer
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      
      initContainers:
      - name: init-installer-dirs
        image: us-central1-docker.pkg.dev/ct2-staging-build/container-images/cleanstart-base:latest-dev
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "=== Init: Creating installer directories ==="
            mkdir -p /shared/extensions /shared/config /shared/logs /shared/tmp
            chmod -R 755 /shared
            
            cat > /shared/config/installer.conf <<'EOF'
            # ArgoCD Extension Installer Configuration
            extension_dir=/shared/extensions
            log_dir=/shared/logs
            temp_dir=/shared/tmp
            EOF
            
            echo "✅ Init: Directories created successfully"
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
      
      containers:
      - name: argocd-extension-installer
        image: us-central1-docker.pkg.dev/ct2-staging-build/staging-community-images/argocd-extension-installer:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 3600; done"]
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        env:
        - name: APPLICATION_TYPE
          value: "argocd-extension-installer"
        - name: HOME
          value: "/home/ext-installer"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - "test -d /home/ext-installer"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: installer-config
          mountPath: /etc/argocd-installer
          readOnly: true
        - name: shared-data
          mountPath: /shared
        - name: tmp-volume
          mountPath: /tmp
        - name: home-volume
          mountPath: /home/ext-installer
      
      - name: test-sidecar
        image: us-central1-docker.pkg.dev/ct2-staging-build/container-images/cleanstart-base:latest-dev
        command: ["sleep", "infinity"]
        env:
        - name: SIDECAR_ROLE
          value: "testing"
        - name: TARGET_APPLICATION
          value: "argocd-extension-installer"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        - name: tmp-volume
          mountPath: /tmp
      
      volumes:
      - name: installer-config
        configMap:
          name: argocd-extension-installer-config
      - name: shared-data
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 100Mi
      - name: home-volume
        emptyDir:
          sizeLimit: 100Mi
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-extension-installer-service
  namespace: argocd-extension-installer
  labels:
    app: argocd-extension-installer
    service-type: clusterip
    framework.version: "4.2.1"
spec:
  selector:
    app: argocd-extension-installer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-extension-installer-nodeport
  namespace: argocd-extension-installer
  labels:
    app: argocd-extension-installer
    service-type: nodeport
    framework.version: "4.2.1"
spec:
  selector:
    app: argocd-extension-installer
  ports:
  - port: 8080
    targetPort: 8080
    # nodePort: 30080
    protocol: TCP
    name: http
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-extension-installer-config
  namespace: argocd-extension-installer
  labels:
    app: argocd-extension-installer
    framework.version: "4.2.1"
data:
  application.type: "argocd-extension-installer"
  installer.conf: |
    # ArgoCD Extension Installer Configuration
    extension_directory=/shared/extensions
    log_directory=/shared/logs
    temp_directory=/shared/tmp
    openssl_version=3.5.0
